services:
  telegram_proxy_server:
    build: .
    image: telegram-proxy-server
    container_name: telegram-proxy-server
    restart: unless-stopped
    ports:
      - "${PORT:-1080}:${PORT:-1080}"
    volumes:
      - ./:/app
